name: E2E test

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # excludes main

jobs:
  e2e-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn

      - name: Create .env file
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" > .env
          echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
          echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env

      - name: Serve site at localhost
        run: (yarn serve&)

      - name: Cache firebase emulator
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/firebase/emulators"
          key: firebase-emulator-v1

      - name: Serve backend
        run: (yarn backend&)

      - name: Install Chrome
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6494C6D6997C215E
          sudo apt-get update
          sudo apt-get install lsb-release libappindicator3-1
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          curl -L -o google-chrome.deb http://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_78.0.3904.108-1_amd64.deb
          sudo apt install ./google-chrome.deb --allow-downgrades
          sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb

      - name: Run e2e
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: cffc111e-174c-4fdb-9545-a2b5e448c5c9
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: false
          record: true
          parallel: false
          env: lang=ja,DEFAULT_COMMAND_TIMEOUT=60000
          wait-on: http://localhost:8080,http://localhost:8081
          wait-on-timeout: 300
          browser: chrome
          headless: true
